version: 2

project_name: zist

before:
  hooks:
    - go mod tidy

builds:
  - id: zist
    main: .
    binary: zist
    env:
      - CGO_ENABLED=1
    flags:
      - -tags=fts5
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - HELP.txt

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: tchaudhry91
    name: zist
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
